### ISSUE TITLE
Doesn't work with Angular 4.2.5

### ISSUE THREAD

**Issue by saostad** [anderlin/ngx-agile-slider#1]
is there any special configuration to use in Angular 4.2.5?

Error:

`app.module.ts (8,31): Cannot find module 'ngx-agile-slider.module'.`

**Comment by anderlin** [comment]
Hi and thank you for creating an issue here.

I will check what exactly the problem is. later on i will update all dependencies.

**Comment by harshitgupta** [comment]
any updates?

**Comment by henkverschoor1994** [comment]
Use ```import { NgxAgileSliderModule } from 'ngx-agile-slider';```
